### ISSUE TITLE
Will be submitted for official ?

### ISSUE THREAD

**Issue by a0a0max** [brigudav/android_device_xiaomi_surya_twrp#3]
Hello,
Are you planning to be mantainer for official twrp for surya?

It would be great.

In any case... Thanks.

**Comment by brigudav** [comment]
> Hello, Are you planning to be mantainer for official twrp for surya?
> 
> It would be great.
> 
> In any case... Thanks.

Hello. Data encryption was broken in the official sources of TWRP, both on our device and on some others. They refuse to correct and do not admit their mistake, so you can’t assemble a fully working official recovery. So there will hardly be an official TWRP in the near future.

**Comment by a0a0max** [comment]
Thanks

**Comment by a0a0max** [comment]
Thanks
