### ISSUE TITLE
Decrypt failed

### ISSUE THREAD

**Issue by walent021** [brigudav/android_device_xiaomi_surya_twrp#4]
Decrypting /data doesn't work on my X3 NFC, saying Password failed, please try again after entering the pin in recovery. (Failed to decrypt user 0). Should the phone pin be used or something else?

**Comment by brigudav** [comment]
Everything works without problems. https://www.androidfilehost.com/?w=files&flid=329007

**Comment by walent021** [comment]
Yes, your file works okay, but the release on github doesn't. Why isn't the androidfilehost file same as the release here?
