### ISSUE TITLE
No Decryption

### ISSUE THREAD

**Issue by juup** [brigudav/android_device_xiaomi_surya_twrp#5]
TWRP itself works for installing ROM, but the /data is not decrypted. There is no windows for password when TWRP starts.
I recognized the version is shown as 3.7.0_12-0 on the device, but 'Manifest: twrp-12.1' in the releases here on github. Tried to update within TWRP and with fastboot with no error, but the version stays old.

**Comment by brigudav** [comment]
This is compiled on the official twrp sources, where the version does not change, only the build date and errors may be present. On their custom builds, many of these errors are corrected and many additions are made. They can be found on telegram channels or https://sourceforge.net/projects/surya-twrp/files/

**Comment by juup** [comment]
Thanks, it works.
